lesson-1/postit-template/config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  resources :posts, except: [:destroy] do
  	resources :comments, only: [:create]
  end

  resources :categories, only: [:new, :create, :show]
end

lesson-1/postit-template/app/models/category.rb
class Category < ActiveRecord::Base
	has_many :post_categories
	has_many :posts, through: :post_categories

	validates :name, presence: true
end

lesson-1/postit-template/app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :post

	validates :body, presence: true
end

lesson-1/postit-template/app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	has_many :comments
	has_many :post_categories
	has_many :categories, through: :post_categories
	
	validates :title, presence: true, length: {minimum: 5}
	validates :description, presence: true
	validates :url, presence: true, uniqueness: true
end

lesson-1/postit-template/app/models/post_category.rb
class PostCategory < ActiveRecord::Base
	belongs_to :post
	belongs_to :category
end

lesson-1/postit-template/app/models/user.rb
class User < ActiveRecord::Base
	has_many :posts
	has_many :comments
end

lesson-1/postit-template/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

lesson-1/postit-template/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

	def new
		@category = Category.new
	end

	def create
		@category = Category.new(category_params)

		if @category.save
			flash[:notice] = "Your category was created."
			redirect_to root_path
		else
			render :new
		end
	end
	
	def show
		@category = Category.find(params[:id])
	end

	private

	def category_params
		params.require(:category).permit(:name)
	end

end

lesson-1/postit-template/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.build(params.require(:comment).permit(:body))
		@comment.user = User.first

		if @comment.save
			flash[:notice] = 'Your comment was added.'
			redirect_to post_path(@post)
		else
			render 'posts/show'
		end
	end
end

lesson-1/postit-template/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update]

  def index
  	@posts = Post.all
  end

  def show
    @comment = Comment.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = User.first # TODO: change once we have authentication
    # binding.pry
    # MEMORIZE the following pattern!
    if @post.save
      flash[:notice] = "Your post was created."
      redirect_to posts_path
    else    # validation error -> why we must render the errors
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      flash[:notice] = "Your post was updated."
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  private

  # strong parameters for security
  def post_params
    # params.require(:post).permit!
    # if user.admin?
    #   params.require(:post).permit!               # permits all attributes
    # else
    params.require(:post).permit(:title, :url, :description, category_ids: [])  # only permits certain attributes that you decide
    # end
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

lesson-1/postit-template/app/helpers/application_helper.rb
# This is for application wide logic
module ApplicationHelper
	def fix_url(str)
		str.starts_with?('http://') ? str : "http://#{str}"
	end

	def display_datetime(dt)
		dt.strftime("%m/%d/%Y %l:%M%P %Z")
	end
end

lesson-1/postit-template/app/views/categories/_category.html.erb
<span class="badge"><%= link_to category.name, category_path(category) %></span>

lesson-1/postit-template/app/views/categories/new.html.erb
<%= render 'shared/content_title', title: "New Category" %>
<%= render 'shared/errors', obj: @category %>

<div class="well">
	<%= form_for @category do |f| %>
		<div class="control-group">
			<%= f.label :name %>
			<%= f.text_field :name %>
		</div>
		<%= f.submit "Create Category", class: "btn btn-success" %>
	<% end %>
</div>

lesson-1/postit-template/app/views/categories/show.html.erb
<% header = link_to("All Posts", posts_path) +  " &raquo; #{@category.name}".html_safe %>
<%= render 'shared/content_title', title: header %>

<% @category.posts.each do |post| %>
	<%= render 'posts/post', post: post %>
<% end %>

lesson-1/postit-template/app/views/comments/new.html.erb
<%= render 'shared/content_title', title: "New Comment" %>
<%= render 'shared/errors', obj: @comment %>

<div class="well">
	<%= form_for @comment do |f| %>
		<div class="control-group">
			<%= f.label :name %>
			<%= f.text_field :name %>
		</div>
		<%= f.submit "Create Comment", class: "btn btn-success" %>
	<% end %>
</div>

lesson-1/postit-template/app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == "notice" ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

lesson-1/postit-template/app/views/layouts/_navigation.html.erb
<ul class="nav">
  <li>
    <%= link_to "Postit!", root_path, :class => 'brand' %>
  </li>
  <li>
    <%= link_to 'link', '' %>
  </li>
</ul>

<div class="btn-group nav_item">
		<%= link_to "#", class: "btn btn-small dropdown-toggle", "data-toggle" => "dropdown" do %>
			Categories <span class="caret"></span>
		<% end %>
		<ul class="dropdown-menu">
			<% Category.all.each do |category| %>
				<li>
					<%= link_to category.name, category_path(category) %>
				</li>
			<% end %>
			<li class="divider"></li>
			<li>
				<%= link_to (new_category_path) do %>
					<i class="icon-plus"></i>
					New Category
				<% end %>
			</li>
		</ul>
</div>

<div class="nav_item">
	<%= link_to 'New Post', new_post_path, class: 'btn btn-success btn-small' %>
</div>

lesson-1/postit-template/app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tealeaf Academy - Postit</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header>
      <div class="navbar">
        <div class="navbar-inner">
          <div class="container">
            <%= render 'layouts/navigation' %>
          </div>
        </div>
      </div>
    </header>
    <div id="main" role="main">
      <div class="container">
         <div class="row">
          <div class="span12">
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div>
        </div>
        <footer>
        </footer>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

lesson-1/postit-template/app/views/posts/_form.html.erb
<%= render 'shared/errors', obj: @post %>

<div class="well">
	<%= form_for @post do |f| %>
		<div class="control-group">
			<%= f.label :title %>
			<%= f.text_field :title %>
		</div>
		<div class="control-group">
			<%= f.label :url %>
			<%= f.text_field :url %>
		</div>
		<div class="control-group">
			<%= f.label :description %>
			<%= f.text_area :description, rows: 5 %>
		</div>
		<div class='control-group'>
			<%= f.label "Categories" %>
			<%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
				<% cb.label(class: "checkbox inline") {cb.check_box(class: "checkbox") + cb.text} %>
			<% end %>
		</div>
		<%= f.submit(@post.new_record? ? "Create Post" : "Update Post", class: "btn btn-primary") %>
	<% end %>
</div>

lesson-1/postit-template/app/views/posts/_post.html.erb
<% @posts.each do |post| %>
	<div class="row">
		<div class="span8 well">
			<% post.categories.each do |category| %>
				<span class="badge"><%= category.name %></span>
			<% end %>
			<h4><%= link_to post.title, fix_url(post.url) %></h4>
			<p><%= post.description %></p>
			<p>
				<span class="quiet">posted by</span> <%= post.user.username %>
				<small><%= display_datetime(post.created_at) %></small>
				<span>
					<%= link_to("#{post.comments.length} comments", post_path(post)) %>
				</span>
			</p>
		</div>
	</div>
<% end %>

lesson-1/postit-template/app/views/posts/edit.html.erb
<h4>Edit this post</h4>

<%= render 'form' %>

lesson-1/postit-template/app/views/posts/index.html.erb
<%= render "shared/content_title", title: "All Posts" %>

<ul>
	<% @posts.each do |post| %>
		<li><%= link_to post.title, post_path(post) %>
		(<%= link_to 'edit', edit_post_path(post) %>)</li>
	<% end %>
</ul>

lesson-1/postit-template/app/views/posts/new.html.erb
<h4>Create a post</h4>

<%= render 'form' %>

lesson-1/postit-template/app/views/posts/old_index.html.erb
<%= render "shared/content_title", title: "All Posts" %>

<% @posts.each do |post| %>
	<%= render "post", post: post %>
<% end %>

lesson-1/postit-template/app/views/posts/show.html.erb
<p class="pull-right">
	[<%= link_to 'edit this post', edit_post_path(@post) %>]
</p>

<p>
	<%= render @post.categories %>
</p>

<%= render 'shared/content_title', title: @post.title %>

<p>
	<%= @post.description %>
</p>
<hr/>

<%= form_for [@post, @comment] do |f| %>
	<%= render 'shared/errors', obj: @comment %>
	<div class="control-group">
		<%= f.label :body, 'Leave a comment' %>
		<%= f.text_area :body, rows: 3, class: 'span4' %>
	</div>
	<%= f.submit "Create comment", class: "btn btn-primary" %>
<% end %>

<h5>Comments:</h5>

<% @post.comments.each do |comment| %>
	<div class="well span8">
		<em>"<%= comment.body %>"</em>
		<br/>
		<span class="quiet">by</span> <%= comment.user.username %>
		<small><%= display_datetime(comment.created_at) %></small>
	</div>
<% end %>

lesson-1/postit-template/app/views/shared/_content_title.html.erb
<p class="lead">
	<%= title %>
	<hr/>
</p>

lesson-1/postit-template/app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
	<div class="alert alert-error">
		<h5>There were some errors:</h5>	
		<ul>
			<% obj.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>